### ISSUE TITLE
Create folder structure in Storybook for Verified and Unverified Components

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system-react#188]
Currently the DSR has one bucket for all components. Some components have been verified but others are just sketches and have not yet gone through full review and QA checks. We would like to create a visual separation so that developers can understand which components are finalized - at a glance. 

## Current behavior
<img width="534" alt="Screenshot 2023-10-02 at 12 53 57 PM" src="https://github.com/cfpb/design-system-react/assets/77348967/be7729fd-4f0a-4493-9d6a-fcfae03b32a5">

## Expected behavior
- Folder for "Verified" components
- Folder for "Unverified components" - @meissadia - Is there a better word for this? 

## Steps to replicate behavior (include URLs)
1.Go to https://cfpb.github.io/design-system-react/?path=/docs/example-introduction--overview
2. View left navigation menu

**Comment by meissadia** [comment]
@natalia-fitzgerald Demo of splitting components between those that have been `Approved` and others still in `Draft` state.   
 
I was struggling to get the original categories (Verified / Unverified) to display in the proper order in the sidebar (ideally: Verified first) due to Storybook applying an alphabetical sort there, hence the change to Approved/Draft, but I can continue exploring how to force the desired display order for whatever group names we settle on.
 
Other grouping ideas:
- Complete / In Progress
- Ready / Pending
- Confirmed / Unconfirmed
- Done / Draft

![Screenshot 2023-10-02 at 4 54 57 PM](https://github.com/cfpb/design-system-react/assets/2592907/a6b62431-f952-4f19-85e8-d414f68b3d59)
