### ISSUE TITLE
Spike: Bring the DS Single and Multiselect into Storybook

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system-react#197]
Explore implementing DSR Select components by matching the Design System's HTML layout instead of attempting to replicate the styling using the `react-select` library. 
 
## Variants
- [Single select](https://cfpb.github.io/design-system/components/selects#single-select)
- [Multi-select](https://cfpb.github.io/design-system/components/selects#multiselect)

## We want to understand  
- What are the Pros / Cons of using primarily HTML instead of the React library?
- Any blockers?

**Comment by meissadia** [comment]
## Single select
I've been able to integrate the Single select successfully. 
 
## Multiselect
The DS multiselect is a highly customized version of the HTML select and has been more difficult but we're close.  

### Issues
- [x] How can we access the internal state of which items are selected?
  - The internal DS select state is not accessible
  - I've implemented a workaround for tracking selected items in the React wrapper's state, which seems to be working well
- [ ] How can we get the icons in the selected Pills to display correctly?
  - Icon gets rendered as a path string instead of the SVG (option 4)
  - I've been able to get as far as stripping out that string but not able to get the actual icon to render (option 2, 3)
  - ![Screenshot 2023-10-18 at 2 35 46 PM](https://github.com/cfpb/design-system-react/assets/2592907/4149ac40-5b6c-46a5-89b1-3f4256e1a369)
  - Potential workaround: Render the pills ourselves, similar to what we were doing with the `react-select` version of the Dropdown
    - Pros: We still use most of the DS select's logic and styles
    - Cons:  
      - May need to reimplement accessibility (thought I think that was already addressed) 
      - Would need to hide DS select's rendered pills 
      - Would need to render our own pills using the same classnames to be able to reuse DS styles

**Comment by meissadia** [comment]
Next steps in DS:
- Explore splitting Tag rendering into separate component from Multiselect
- Explore exposing the Multiselect model for easier integration

**Comment by meissadia** [comment]
Status as of 11/7:
- (Local) integration of the DS Select and Multiselect into DSR has been successful! 
- Work here is blocked by https://github.com/cfpb/design-system/pull/1801, which provides the modifications to the DS Select that we need in order to properly integrate this component into the DSR
- Unit tests have been written 👍🏾

**Comment by meissadia** [comment]
- Tried adding a jest.config.js to apply 'jest-svg-transformer'

 FAIL  src/components/Select/Select.test.tsx [ src/components/Select/Select.test.tsx ]
 FAIL  src/components/TextIntroduction/TextIntroduction.test.tsx [src/components/TextIntroduction/TextIntroduction.test.tsx ]
 FAIL  src/components/Link/Link.test.tsx [ src/components/Link/Link.test.tsx ]
 FAIL  src/components/Well/Well.test.tsx [ src/components/Well/Well.test.tsx ]
 FAIL  src/components/Alert/Alert.test.tsx [ src/components/Alert/Alert.test.tsx ]
 FAIL  src/components/TextInput/TextInput.test.tsx [ src/components/TextInput/TextInput.test.tsx ]
 FAIL  src/components/Table/Table.test.tsx [ src/components/Table/Table.test.tsx ]

**Comment by meissadia** [comment]
- Tried all the resolutions I found online, none worked for us.
    - `error.svg` is only directly used in DS Multiselect?
    - In DS the SVG gets directly injected as code: https://cfpb.github.io/design-system/components/selects#multiselect

**Comment by meissadia** [comment]
Interesting point of note: The following fixes the issue of DS icons not rendering in Vite!!!  I don't know the wider implications of using this approach, but it does allow DS rendered icons to show up correctly in DSR.

In vite.config.ts
```
svgLoader({
  defaultImport: 'raw'
}),
```
